services:
  mongo:
    image: mongo:8.0.0
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mongo/db/:/data/db/
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password 
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.18.2
    container_name: swagger-ui
    restart: unless-stopped
    ports:
      - 8084:8080
    volumes:
      - ./api-doc/openapi.yml:/openapi.yml:ro
    environment:
      - SWAGGER_JSON=/openapi.yml
