name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 或者你希望触发的分支
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: wangyucode
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read package.json version
        id: read-version
        run: |
          echo "::set-output name=VERSION::$(jq -r .version package.json)"
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            wangyucode/node-backend:latest
            wangyucode/node-backend:${{ steps.read-version.outputs.VERSION }}

      - name: upload api docs
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: "wycode.cn"
          privateKey: ${{ secrets.SERVER_KEY }}
          localDir: "api-doc"
          dryRun: false
          compress: true
          remoteDir: "/root/data/www/swagger-ui/"
